import { IsOptional, IsString } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';

export class VerifyRazorpayDto {
  @ApiPropertyOptional({ example: 'order_9A33XWu170gUtm', description: 'Razorpay Order ID' })
  @IsString()
  @IsOptional()
  razorpayOrderId?: string;

  @ApiPropertyOptional({ example: 'order_9A33XWu170gUtm', description: 'Razorpay Order ID (snake_case alternative)' })
  @IsString()
  @IsOptional()
  razorpay_order_id?: string;

  @ApiPropertyOptional({ example: 'pay_2989dh82h', description: 'Razorpay Payment ID' })
  @IsString()
  @IsOptional()
  razorpayPaymentId?: string;

  @ApiPropertyOptional({ example: 'pay_2989dh82h', description: 'Razorpay Payment ID (snake_case alternative)' })
  @IsString()
  @IsOptional()
  razorpay_payment_id?: string;

  @ApiPropertyOptional({ example: '9ef4d79b23991a25786f8662', description: 'HMAC SHA256 signature generated by Razorpay client SDK' })
  @IsString()
  @IsOptional()
  razorpaySignature?: string;

  @ApiPropertyOptional({ example: '9ef4d79b23991a25786f8662', description: 'HMAC SHA256 signature (snake_case alternative)' })
  @IsString()
  @IsOptional()
  razorpay_signature?: string;
}
